---
include:
  # Eyeslash Corne is a wireless Corne keyboard from AliExpress.
  # It also has a dongle, which seems to be a clone of https://github.com/englmaxi/zmk-dongle-display
  # - AliExpress product: https://www.aliexpress.com/item/1005009056257222.html
  # - Firmware config: https://github.com/a741725193/zmk-sofle-dongle/
  - board: nice_nano_v2
    shield: eyeslash_corne_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DEXTRA_CONF_FILE=../../config/central.conf
    artifact-name: corne_central_dongle_oled

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DEXTRA_CONF_FILE=../../config/central.conf
    artifact-name: corne_left_central_oled

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    artifact-name: corne_left_oled

  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne_right_oled

  - board: nice_nano_v2
    shield: corne_right
    snippet: zmk-usb-logging
    artifact-name: corne_right_trackpad

  # debug
  - board: nice_nano_v2
    shield: corne_left
    snippet: zmk-usb-logging
    artifact-name: corne_left_dbg

  - board: nice_nano_v2
    shield: corne_right
    snippet: zmk-usb-logging
    artifact-name: corne_right_dbg

  # reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: corne_reset_settings
