---
include:
  # Eyeslash Corne is a wireless Corne keyboard from AliExpress.
  # It also has a dongle, which seems to be a clone of https://github.com/englmaxi/zmk-dongle-display
  # - AliExpress product: https://www.aliexpress.com/item/1005009056257222.html
  # - Firmware config: https://github.com/a741725193/zmk-sofle-dongle/
  - board: nice_nano_v2
    shield: eyeslash_corne_central_dongle dongle_display cirque_pinnacle_central
    snippet: studio-rpc-usb-uart
    artifact-name: corne_dongle

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view cirque_pinnacle_central
    snippet: studio-rpc-usb-uart
    artifact-name: corne_left_central

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    artifact-name: corne_left

  - board: nice_nano_v2
    shield: corne_right cirque_pinnacle_adapter cirque_pinnacle_trackpad
    cmake-args: -DDTC_OVERLAY_FILE=../../config/trackpad.overlay
    artifact-name: corne_right

  # debug
  - board: nice_nano_v2
    shield: eyeslash_corne_central_dongle dongle_display cirque_pinnacle_central
    snippet: studio-rpc-usb-uart cdc-acm-console
    cmake-args: -DCONFIG_SHELL=y -DCONFIG_SHELL_LOG_BACKEND=y -DCONFIG_SENSOR_SHELL=n -DCONFIG_ZMK_USB_LOGGING=y -DCONFIG_INPUT_LOG_LEVEL_DBG=y # -DCONFIG_SERIAL=y -D CONFIG_CONSOLE=y
    artifact-name: corne_dongle_dbg

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view cirque_pinnacle_central
    snippet: studio-rpc-usb-uart cdc-acm-console
    cmake-args: -DCONFIG_SHELL=y -DCONFIG_SHELL_LOG_BACKEND=y -DCONFIG_SENSOR_SHELL=n -DCONFIG_ZMK_USB_LOGGING=y -DCONFIG_INPUT_LOG_LEVEL_DBG=y # -DCONFIG_SERIAL=y -D CONFIG_CONSOLE=y
    artifact-name: corne_left_central_dbg

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart cdc-acm-console
    cmake-args: -DCONFIG_SHELL=y -DCONFIG_SHELL_LOG_BACKEND=y -DCONFIG_SENSOR_SHELL=n -DCONFIG_ZMK_USB_LOGGING=y -DCONFIG_INPUT_LOG_LEVEL_DBG=y # -DCONFIG_SERIAL=y -D CONFIG_CONSOLE=y
    artifact-name: corne_left_dbg

  - board: nice_nano_v2
    shield: corne_right cirque_pinnacle_adapter cirque_pinnacle_trackpad
    snippet: studio-rpc-usb-uart cdc-acm-console
    cmake-args: -DDTC_OVERLAY_FILE=../../config/trackpad.overlay -DCONFIG_SHELL=y -DCONFIG_SHELL_LOG_BACKEND=y -DCONFIG_SENSOR_SHELL=n -DCONFIG_ZMK_USB_LOGGING=y -DCONFIG_INPUT_LOG_LEVEL_DBG=y # -DCONFIG_SERIAL=y -D CONFIG_CONSOLE=y
    artifact-name: corne_right_dbg

  # barebones
  - board: nice_nano_v2
    shield: eyeslash_corne_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: corne_dongle_min

  - board: nice_nano_v2
    shield: corne_left
    artifact-name: corne_left_min

  - board: nice_nano_v2
    shield: corne_right
    artifact-name: corne_right_min

  # reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: corne_reset_settings
