# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # Eyeslash Corne is a wireless Corne keyboard from AliExpress.
  # It also has a dongle, which seems to be a clone of https://github.com/englmaxi/zmk-dongle-display
  # - AliExpress product: https://www.aliexpress.com/item/1005009056257222.html
  # - Firmware config: https://github.com/a741725193/zmk-sofle-dongle/
  - board: nice_nano_v2
    shield: eyeslash_corne_central_dongle dongle_display cirque_pinnacle_central
    snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_BT_MAX_CONN=6 -DCONFIG_BT_MAX_PAIRED=6 -DCONFIG_ZMK_DISPLAY=y -DCONFIG_ZMK_USB=y -DZMK_POINTING_SMOOTH_SCROLLING=y
    artifact-name: corne_central_dongle_oled

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view cirque_pinnacle_central
    snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_BT_MAX_CONN=6 -DCONFIG_BT_MAX_PAIRED=6 -DCONFIG_ZMK_USB=y -DZMK_POINTING_SMOOTH_SCROLLING=y
    artifact-name: corne_left_central_oled

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    artifact-name: corne_left_oled

  - board: nice_nano_v2
    shield: corne_right cirque_pinnacle_adapter cirque_pinnacle_trackpad
    # cmake-args: -DCONFIG_ZMK_DISPLAY=n -DCONFIG_ZMK_POINTING=y -DCONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y -DZMK_SPLIT=y
    artifact-name: corne_right

  # reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: corne_reset_settings
