---
include:
  # Eyeslash Corne is a wireless Corne keyboard from AliExpress.
  # It also has a dongle, which seems to be a clone of https://github.com/englmaxi/zmk-dongle-display
  # - AliExpress product: https://www.aliexpress.com/item/1005009056257222.html
  # - Firmware config: https://github.com/a741725193/zmk-sofle-dongle/

  - board: nice_nano_v2
    shield: eyeslash_corne_central_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_BT_MAX_CONN=6 -DCONFIG_BT_MAX_PAIRED=6 -DCONFIG_ZMK_DISPLAY=y -DCONFIG_ZMK_USB=y
    artifact-name: corne_central_dongle_oled

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_BT_MAX_CONN=6 -DCONFIG_BT_MAX_PAIRED=6 -DCONFIG_ZMK_USB=y
    artifact-name: corne_left_central_oled

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: corne_left_oled

  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_custom
    cmake-args: -DCONFIG_ZMK_STUDIO=n -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
    artifact-name: corne_right_oled

  - board: nice_nano_v2
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_STUDIO=n -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_DISPLAY=n
    artifact-name: corne_right

  # reset
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: corne_reset_settings
