manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: juniorz
      url-base: https://github.com/juniorz

    - name: englmaxi
      url-base: https://github.com/englmaxi

    - name: petejohanson
      url-base: https://github.com/petejohanson

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    # dongle shield with corne layout
    - name: zmk-corne-dongle
      remote: juniorz
      revision: main

    # cirque pinnacle
    - name: zmk-keyboard-cirque-pinnacle
      remote: juniorz
      revision: main
      import: west.yml

    - name: zmk-dongle-display
      remote: englmaxi
      revision: main

    # - name: zmk-analog-input-driver
    #   remote: badjeff
    #   revision: main
    # - name: zmk-split-peripheral-input-relay
    #   remote: badjeff
    #   revision: main
    # - name: zmk-split-peripheral-output-relay
    #   remote: badjeff
    #   revision: main
    - name: cirque-input-module
      remote: petejohanson
      revision: main
      # revision: feat/idle-waker-wake-from-sleep-fixes

  self:
    path: config
