manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: juniorz
      url-base: https://github.com/juniorz

    - name: englmaxi
      url-base: https://github.com/englmaxi

    # - name: petejohanson
    #   url-base: https://github.com/petejohanson

    - name: gpeye
      url-base: https://github.com/GPeye

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      clone-depth: 1
      import: app/west.yml

    # This has fixed to cdc_ecm
    - name: zephyr
      remote: juniorz
      revision: v3.5.0+zmk-fixes+patches
      clone-depth: 1
      import:
        name-blocklist:
          - ci-tools
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_silabs
          - hal_xtensa
          - hal_st
          - hal_ti
          - loramac-node
          - mcuboot
          - mcumgr
          - net-tools
          - openthread
          - edtt
          - trusted-firmware-m

    # dongle shield with corne layout
    - name: zmk-corne-dongle
      remote: juniorz
      revision: main

    # cirque pinnacle
    - name: zmk-keyboard-cirque-pinnacle
      remote: juniorz
      revision: main
      import: west.yml

    - name: zmk-dongle-display
      remote: englmaxi
      revision: main

    # - name: zmk-analog-input-driver
    #   remote: badjeff
    #   revision: main
    # - name: zmk-split-peripheral-input-relay
    #   remote: badjeff
    #   revision: main
    # - name: zmk-split-peripheral-output-relay
    #   remote: badjeff
    #   revision: main

    # - name: cirque-input-module
    #   remote: petejohanson
    #   revision: main

    # - name: mario-peripheral-animation
    #   remote: gpeye
    #   revision: main
    # - name: hammerbeam-slideshow
    #   remote: gpeye
    #   revision: main

  self:
    path: config
