manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: a741725193
      url-base: https://github.com/a741725193

    - name: englmaxi
      url-base: https://github.com/englmaxi

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    # dongle shield with corne layout
    - name: zmk-corne-dongle
      remote: a741725193
      revision: main

    - name: zmk-dongle-display
      remote: englmaxi
      revision: main

  self:
    path: config
