manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: juniorz
      url-base: https://github.com/juniorz

    - name: englmaxi
      url-base: https://github.com/englmaxi

    - name: gpeye
      url-base: https://github.com/GPeye

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    # dongle shield with corne layout
    - name: zmk-corne-dongle
      remote: juniorz
      revision: main

    - name: zmk-dongle-display
      remote: englmaxi
      revision: main

    - name: mario-peripheral-animation
      remote: gpeye
      revision: main

    # - name: hammerbeam-slideshow
    #   remote: gpeye
    #   revision: main

  self:
    path: config
